import {
	index,
	integer,
	jsonb,
	pgTable,
	text,
	timestamp,
} from "drizzle-orm/pg-core";

export const countries = pgTable(
	"countries",
	{
		id: integer("id").primaryKey(),
		name: text("name").notNull(),
		iso3: text("iso3").notNull().unique(),
		iso2: text("iso2").notNull().unique(),
		numericCode: text("numeric_code"),
		phonecode: text("phonecode"),
		capital: text("capital"),
		currency: text("currency"),
		currencyName: text("currency_name"),
		currencySymbol: text("currency_symbol"),
		tld: text("tld"),
		native: text("native"),
		region: text("region"),
		subregion: text("subregion"),
		nationality: text("nationality"),
		timezones: jsonb("timezones"),
		translations: jsonb("translations"),
		latitude: text("latitude"),
		longitude: text("longitude"),
		emoji: text("emoji"),
		emojiU: text("emojiU"),
		wikiDataId: text("wiki_data_id"),
		population: integer("population"),
		gdp: integer("gdp"),
		regionId: integer("region_id"),
		subregionId: integer("subregion_id"),
		areaSqKm: integer("area_sq_km"),
		postalCodeFormat: text("postal_code_format"),
		postalCodeRegex: text("postal_code_regex"),
		createdAt: timestamp("created_at").defaultNow(),
		updatedAt: timestamp("updated_at").defaultNow(),
	},
	(table) => [
		index("countries_name_idx").on(table.name),
		index("countries_region_idx").on(table.region),
	],
);
