/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SeasonsRouteImport } from './routes/seasons'
import { Route as HolidaysRouteImport } from './routes/holidays'
import { Route as CountriesInfoRouteImport } from './routes/CountriesInfo'
import { Route as ContinuousCalendarRouteImport } from './routes/ContinuousCalendar'
import { Route as IndexRouteImport } from './routes/index'

const SeasonsRoute = SeasonsRouteImport.update({
  id: '/seasons',
  path: '/seasons',
  getParentRoute: () => rootRouteImport,
} as any)
const HolidaysRoute = HolidaysRouteImport.update({
  id: '/holidays',
  path: '/holidays',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesInfoRoute = CountriesInfoRouteImport.update({
  id: '/CountriesInfo',
  path: '/CountriesInfo',
  getParentRoute: () => rootRouteImport,
} as any)
const ContinuousCalendarRoute = ContinuousCalendarRouteImport.update({
  id: '/ContinuousCalendar',
  path: '/ContinuousCalendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ContinuousCalendar': typeof ContinuousCalendarRoute
  '/CountriesInfo': typeof CountriesInfoRoute
  '/holidays': typeof HolidaysRoute
  '/seasons': typeof SeasonsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ContinuousCalendar': typeof ContinuousCalendarRoute
  '/CountriesInfo': typeof CountriesInfoRoute
  '/holidays': typeof HolidaysRoute
  '/seasons': typeof SeasonsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ContinuousCalendar': typeof ContinuousCalendarRoute
  '/CountriesInfo': typeof CountriesInfoRoute
  '/holidays': typeof HolidaysRoute
  '/seasons': typeof SeasonsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ContinuousCalendar'
    | '/CountriesInfo'
    | '/holidays'
    | '/seasons'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ContinuousCalendar' | '/CountriesInfo' | '/holidays' | '/seasons'
  id:
    | '__root__'
    | '/'
    | '/ContinuousCalendar'
    | '/CountriesInfo'
    | '/holidays'
    | '/seasons'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContinuousCalendarRoute: typeof ContinuousCalendarRoute
  CountriesInfoRoute: typeof CountriesInfoRoute
  HolidaysRoute: typeof HolidaysRoute
  SeasonsRoute: typeof SeasonsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/seasons': {
      id: '/seasons'
      path: '/seasons'
      fullPath: '/seasons'
      preLoaderRoute: typeof SeasonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/holidays': {
      id: '/holidays'
      path: '/holidays'
      fullPath: '/holidays'
      preLoaderRoute: typeof HolidaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/CountriesInfo': {
      id: '/CountriesInfo'
      path: '/CountriesInfo'
      fullPath: '/CountriesInfo'
      preLoaderRoute: typeof CountriesInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ContinuousCalendar': {
      id: '/ContinuousCalendar'
      path: '/ContinuousCalendar'
      fullPath: '/ContinuousCalendar'
      preLoaderRoute: typeof ContinuousCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContinuousCalendarRoute: ContinuousCalendarRoute,
  CountriesInfoRoute: CountriesInfoRoute,
  HolidaysRoute: HolidaysRoute,
  SeasonsRoute: SeasonsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
